name: On Push to Master

on:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Install dependencies 👨🏻‍💻
        run: npm ci

      - name: Run linter 👀
        run: npm run lint

      - name: Generate static files
        run: npm run generate

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KRONHYX }}'
          channelId: live
          projectId: kronhyx
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
